version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-bookstore
    restart: always
    environment:
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: books
    ports:
      - "9999:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookuser -d bookstore"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local